### PR TITLE
Update submodules to match master

### PR DESCRIPTION
**Pull request by rljacob**
Update several submodules to match upstream master.
3 that a test merge said were a conflict:  scorpio_classic, YAKL and rrtmpg
Update 3 others to match latest E3SM master: cosp2, gotm, scorpio.

### CODE REVIEW

**Comment by rljacob** [comment]
Tested with a 1 day ne4 coupled run on Chrysalis.  Ran fine.

**Comment by rljacob** [comment]
@sarich can you make sure this compiles/runs ok on GCE?

**Review by sarich — APPROVED** [review]
Works for me on GCE

**Comment by rljacob** [comment]
Good this got rid of the submodule conflicts in #9

**Pull request merged**
